# Generated by Django 4.0.5 on 2022-06-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer_rename_created_on_ordermodel_date_ordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='date_ordered',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='transaction_id',
        ),
    ]
