# Generated by Django 4.0.5 on 2022-06-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_ordermodel_email_ordermodel_location_ordermodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
