# Generated by Django 4.0.5 on 2022-06-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_ordermodel_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
