# Generated by Django 4.0.5 on 2022-06-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_shipped',
        ),
    ]
